# Generated by Django 4.1 on 2022-08-16 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.IntegerField(default='DEFAULT VALUE', primary_key=True, serialize=False)),
                ('categoria_nombre', models.TextField(max_length=40)),
                ('categoria_fecha_acualizacion', models.TextField()),
                ('categoria_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria_vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.IntegerField(default='DEFAULT VALUE', primary_key=True, serialize=False)),
                ('pedido_numero', models.IntegerField()),
                ('pedido_entregado', models.BooleanField(default=True)),
                ('pedido_fecha_actualizacion', models.TextField()),
                ('pedido_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido_vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.IntegerField(default='DEFAULT VALUE', primary_key=True, serialize=False)),
                ('run', models.TextField()),
                ('primer_nombre', models.TextField(max_length=40)),
                ('segundo_nombre', models.TextField(default='', max_length=40)),
                ('primer_apellido', models.TextField(max_length=40)),
                ('segundo_apellido', models.TextField(max_length=40)),
                ('correo_electronico', models.TextField(max_length=70)),
                ('direccion', models.TextField()),
                ('region', models.TextField(max_length=40)),
                ('ciudad', models.TextField(max_length=40)),
                ('fecha_nacimiento', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_vigencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.IntegerField(default='DEFAULT VALUE', primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('prod_nombre', models.TextField(max_length=30)),
                ('prod_descripcion', models.TextField()),
                ('prod_fecha_acualizacion', models.TextField()),
                ('prod_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prod_vigencia', models.BooleanField(default=True)),
                ('categoria_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
                ('usuario_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
