# Generated by Django 4.1 on 2022-08-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.IntegerField(default='DEFAULT VALUE', primary_key=True, serialize=False),
        ),
    ]
