# Generated by Django 4.1 on 2022-08-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.TextField(blank=True, default='DEFAULT VALUE', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, default='DEFAULT VALUE', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.TextField(blank=True, default='DEFAULT VALUE', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.TextField(blank=True, default='', max_length=40, null=True),
        ),
    ]
