# Generated by Django 4.1 on 2022-08-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_categoria_categoria_id_alter_pedido_pedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primer_apellido',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='region',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='run',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
