# Generated by Django 4.1 on 2022-09-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_usuario_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prod_imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
