# Generated by Django 4.1 on 2022-09-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_producto_prod_imagen_alter_producto_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
