# Generated by Django 4.1 on 2022-10-27 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('home', '0010_rename_region_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='categoria_nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='usuario_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.usuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
