# Generated by Django 4.1 on 2022-10-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_categoria_categoria_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
