# Generated by Django 4.1 on 2022-10-27 01:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(blank=True, max_length=20, null=True)),
                ('nombres', models.CharField(blank=True, max_length=220, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=220, null=True)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=220, null=True)),
                ('usuario', models.CharField(blank=True, max_length=220, null=True)),
                ('contrasenna', models.CharField(blank=True, max_length=220, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=220, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=220, null=True)),
                ('comuna', models.CharField(blank=True, max_length=220, null=True)),
                ('direccion', models.CharField(blank=True, max_length=220, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_vigencia', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
