# Generated by Django 4.1 on 2022-11-02 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_contrasenna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasenna',
        ),
    ]
